### ISSUE TITLE
Shot the Greenlink dispatchers an alert e-mail when a trolley isn't online during a scheduled route

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#100] opened 2015-10-20 23:42 UTC
https://codeforgvl.imaginethat.io/trolleytracker/i/5426

**Comment by bikeoid** [comment] 2015-10-21 03:10
Can this be defined as

 * Email when 2 trolleys aren't online during all scheduled routes except for Lunch Link which normally has only 1 trolley running.
 * Check  once per hour, but only a maximum of 1? notification email per day if not running to avoid nuisance emails.
 * Should the email notification be re-sent if the trolley shows up then goes offline an hour later?

**Comment by ajhodges** [comment] 2015-10-21 11:35
* Maybe a scheduled route could have another parameter like "expected number of trolleys running"?
* Checking every hour should be frequent enough to make this effective, I think. Maybe limit it to 1 notification e-mail per trolley, per outage (so if a trolley isn't running at first, and the driver turns on the tablet without plugging it in, and it dies early on in the route, they get another email about it?). Maybe the e-mail could have a link where the dispatcher could suppress the warning somehow?

This was just kind of an idea I had while I was thinking of ways we could improve the consistency of our trolley data. I didn't think much about the implementation, and I'm not sure if it's even a good idea! Welcome to further brainstorming :)

**Comment by bikeoid** [comment] 2015-10-21 12:05
Is Greenlink dispatch open to this idea?

Is the consistency of trolley online operation the only thing that is holding up the public rollout?

**Comment by ajhodges** [comment] 2015-10-21 13:49
I'm not sure, but I think there needs to be some way of alerting them that a trolley is offline. From my perspective it seems like this is the last major hurdle. The Android app is almost ready to go for v1.0. But it's going to leave a bad taste in the users mouth if the trolleys only show up part of the time, leading to bad reviews and poor user retention. Maybe this should be an open dialogue between us an Greenlink. Input, @agautsc?

**Comment by agautsc** [comment] 2015-10-21 18:26
From Greenlink: "There is no one in dispatch on Sat night or Sunday when the trolleys are running. The alert would have to go to the ops person on call - was Dawain, now is Steve."

Maybe we can make a simple status page that shows which trolleys are up and running at the current time and have a way for folks to signup for alerts when a trolley isn't showing. That way it would allow Dawain or Steve or anyone @greenlinktransit signup for alerts.

Maybe we could even have a status on the user app itself letting folks know that both trolleys are running and showing or one trolley is currently offline or some such. We did get an email yesterday that was very happy with the app, but also added  "I know there are two trolleys and at times it only showed one.  I was guessing that the other one was on break.  Is there a way to indicate that or let visitors know that there is another one due to come into service shortly?  Thanks again."

I know @allella and some of the Ruby folks are working on some type of Status page for OpenWorks. Maybe there can be some overlap on status page work.

**Comment by bikeoid** [comment] 2015-10-21 18:43
I just remembered that the drivers want to be able to view the app while they're on the route - that way they would also immediately know that their beacon isn't working.    The biggest problem might be that the tablet would need to auto adjust the intensity low enough that their night vision would not be impaired by the tablet light.

**Comment by ajhodges** [comment] 2015-10-21 20:09
Well the thing of it is, if the drivers have the tablets turned on and the client app is working, then I am 90% sure the agent would be successfully running at that point. It still seems to me that the issue is with tablets being unplugged and/or not turned on.

Of course, you could argue that if the drivers got used to seeing the trolley map on the tablet, they would be more prone to plug the tablets in/turn them on.

A status page is a good idea, if Greenlink will actively check it/subscribe to it. I think if we want this to really be consistent we will need to get them involved and committed at some level. I'd love to help out, but if I jump on an offline trolley and tell a driver to turn their trolley on, I'm fairly certain they'll ignore me. This is something the needs to come from dispatch/ops/whatever.

All that assuming the issues are stemming from the tablet not being powered on and not a bug in the agent or issues with the trolley wifi...

**Comment by ajhodges** [comment] 2015-10-21 20:14
Then there are the hardware-aids that might help us out, such as a tamper-proof micro USB plug for the tablets and/or a micro USB splitter (to let them charge their own phones), and possibly a green sticker or something on the power button to help drivers find it.

**Comment by bikeoid** [comment] 2015-10-22 01:26
I'd prefer that the drivers get the trolley / route display, but I think that may not be realistic in the short term.

If there's any way to have power up tied to the ignition to automatically start the tablet, which would remove the item from the driver's checklist and one less thing to go wrong.   Then if is still intermittent, we would know that it's something else like the WiFi.   I don't know the politics, but if there's any way we could meet to discuss possible solutions, I'm willing to make the time and be there also.

**Comment by greenlinktransit** [comment] 2015-10-22 11:51
Guys -- You bring up a lot of good points.  To give you a little more background on our schedules, regular fixed route buses run until 7:30 PM on weekdays, 6:30 PM on Saturdays, and they do not run on Sundays.  Our dispatchers and OPS team are not on duty unless the fixed route buses are running.  So...from 7:30 PM - 11:00 PM on Thursdays & Fridays, from 6:30 PM - 11:00 PM on Saturdays, and from 1:00 PM - 8:00 PM (all day) on Sunday we do not have anyone from Greenlink monitoring the Trolleys.  If they run into any trouble we have a couple mechanics on duty who will pull them off of their route and try to make the fix.  

The good news is that on Thursday, Friday, & Saturday we have dispatchers who are on duty when the Trolley first goes into service.  So, they should be able to make sure that the drivers turn on their tablets during those days.  Sunday, however, becomes problematic because no on is on duty.

To further complicate the situation, we sometimes need to pull Trolleys out of service to fill a hole for another service.  For instance, last Friday the City asked us to shuttle people for a special event.  We had originally planned on using a small bus, but there were more than 500 people waiting for the bus, so we had to pull the Trolley out of service and help with the shuttling.  This doesn't happen often, but you guys should know that it's a problem we sometimes have.

Anyway, I'm out of town on business this week but would be happy to meet with you next week.  Just let me know when and where.

**Comment by bikeoid** [comment] 2015-10-26 14:01
Which day would work best to meet?  For me, it would be Tuesday or Wednesday, but possibly Monday afternoon.

**Comment by greenlinktransit** [comment] 2015-10-26 14:18
I'm free tomorrow (Tuesday) afternoon and all day Wednesday.  If you want to meet regularly, Wednesday would work best for me.

**Comment by agautsc** [comment] 2015-10-26 18:26
Could y'all meet at 10am on Wednesday at Greenlink? I'll already be there for the UTC board meeting earlier that morning.

**Comment by agautsc** [comment] 2015-10-26 18:27
Or... it might be better to do something after work so more folks could attend. I'm open to whatever works the best.

**Comment by greenlinktransit** [comment] 2015-10-26 18:34
I'm free all day, so let me know what you guys decide.

**Comment by bikeoid** [comment] 2015-10-27 00:36
I propose 10am Wednesday at Greenlink so that there is more time to address any possible action items before Thursday's trolley route start.

**Comment by greenlinktransit** [comment] 2015-10-27 12:49
Works for me.  I'll book the Greenlink conference room for 10AM. Just come in the front door (100 McBee) and our receptionist will let you in.

**Comment by bikeoid** [comment] 2015-10-31 12:34
Monitoring app is online.   Public page of the text notifications and replies is at http://yeahthatmonitor.azurewebsites.net/SMSMessages . Checks at 10,20,30 and 40 minutes past the hour.   3 consecutive instances of not all trolleys showing will result in a text.    This is trying to avoid false positives but not running the whole day with no one aware that it is down.

Steve will not be added yet until I'm confident that it works correctly.   Anyone else can request to get on the text notification list - send me a PM with the number to add.

**Closed by bikeoid** 2015-10-31 12:34 UTC
Labels: enhancement

**Comment by ajhodges** [comment] 2015-10-31 14:22
Wow this is really snazzy! Awesome work, I'll email you my cell number.
